[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]

actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
actix-cors = "0.6"
meval = "0.2"  # A crate for evaluating math expressions
